# Generated by Django 4.2.6 on 2023-10-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('medida', models.CharField(choices=[('option1', 'Metro Cuadrado'), ('option2', 'Metro Cubico'), ('option3', 'Kilo')], max_length=20, verbose_name='Medida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('imagen', models.ImageField(null=True, upload_to='img/uploads', verbose_name='Imagen')),
            ],
        ),
    ]
