# Generated by Django 4.2.6 on 2023-11-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.cart')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.material')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='materials',
            field=models.ManyToManyField(through='pagina.CartMaterial', to='pagina.material'),
        ),
    ]
