# Generated by Django 4.2.6 on 2023-11-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_rename_session_id_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='medida',
            field=models.CharField(choices=[('option1', 'Metro Cuadrado'), ('option2', 'Metro Cubico'), ('option3', 'Kilo'), ('option4', 'Unidad')], max_length=20, verbose_name='Medida'),
        ),
    ]
